### ISSUE TITLE
[enhancement] multiple selections in "MoreClipboard Contents" view

### ISSUE THREAD

**Issue by anb0s** [mikhail-barg/moreclipboard#3]
During working i have lot of content In "MoreClipboard Contents" view and want to select more then one line with
1. holding "ctrl" key and selecting with left mouse button or space key --> add line to multiselection
2. holding "shift" key and selecting with left mouse button or space key --> add all lines from current to selected line to multiselection

Additionally it would be nice if one can use "up" and "down" keys to move the selection during holding "ctrl" or "shift" keys and then only press the space key --> working with keyboard instead with mouse is faster for coders ;)

"Remove current" should be renamed to "Remove selected" then...

**Comment by anb0s** [comment]
related to #2 pressing the delete key should remove all selected entries

**Comment by mikhail-barg** [comment]
Hm.. will see, the code is a bit too old, so I don't remember excactly, but should be possible too! Thanks for the feedback! 

Could you also explain a bit on your use-cases for the MC Contents view? I haven't had any clear vision for it's use-cases when designing it, and I actually thought it's not used ) So I'd like to know more on how it could be useful.

**Comment by anb0s** [comment]
I'm using it as small "code snippet" stack during manual code refactoring or reorganizing. May be it's an overkill, but it's easier if i want just copy some content to stack and just paste it during the working at one task. So i find it useful, because it's the only place to organize collected (i do Ctrl+C very often ;) entries: move up or down, delete not needed entries etc. So for me the "Remove all" button is sometimes risky because deleting the content unintended...

Thanks!

**Comment by mikhail-barg** [comment]
By the way, do you want multiple selection to work just for mass deletion of items, or for moving up/down too? or maybe other uses?

**Comment by anb0s** [comment]
My first use case is just for deletion --> partial clean up of not needed entries. But to have it consistent i think support of moving selected items (block wise) together would be nice too ;) but we can create new request if really needed later...

**Comment by mikhail-barg** [comment]
Ok, then I'll stick with just deletion for now.

**Comment by mikhail-barg** [comment]
Done

**Comment by anb0s** [comment]
verified with v1.4.1 --> works like expected :+1:
