### ISSUE TITLE
[enhancement] pasting content from outside eclipse to "MoreClipboard Contents" view

### ISSUE THREAD

**Issue by anb0s** [mikhail-barg/moreclipboard#4]
I often copy strings from other editors, web browsers, file browsers etc. to eclipse editors and want to have them in clipboard history. So it would be good if Ctrl+V in "MoreClipboard Contents" view adds the clipboard content to the view, so one can paste it later with MoreClipboard.

**Comment by mikhail-barg** [comment]
Good point. Will check it too.

For now, you may have it working as well — it's not obvious but when you press Ctrl+C to copy something from inside the Eclipse, MC first checks the current Clipboard contents and if it is absent in the history - adds it. So if you copy something from browser, and then copy from Eclipse, you'll have both strings in MC Contents.

**Comment by mikhail-barg** [comment]
Done

**Comment by anb0s** [comment]
Thanks!

**Comment by anb0s** [comment]
verified with v1.4.1 --> works like expected :+1:
