### ISSUE TITLE
[enhancement] copying content from "MoreClipboard Contents" view to other tools

### ISSUE THREAD

**Issue by anb0s** [mikhail-barg/moreclipboard#5]
opposite way to issue #4 --> copy from moreclipboard history and paste it in other tools.

**Comment by mikhail-barg** [comment]
Done

**Comment by anb0s** [comment]
Thanks!

**Comment by anb0s** [comment]
cool, thanks!

btw. do you have a test build or a plan when it will be released?

**Comment by mikhail-barg** [comment]
Actually it is released. But it seems that the update site is not working properly - still shows 1.3.0 as a current version. 

And I'm in doubt on why. I'm also getting that `Server returned lastModified <= 0` messages (see https://github.com/anb0s/logviewer/issues/80), so it looks like github does not return the last-modified header and some stuff is being cached.

But I'm not sure if this is a real cause. I've added the release so you could download and try binaries, but would also appreciate your help with investigationg the update site issue. I've also updated my old sourceforge update tite, but it seem to work propely only in E3 builds.

**Comment by anb0s** [comment]
verified with v1.4.1 --> works like expected :+1:
